---
form_fields:
  - legend_i18n_key: equipment_details
    fields:
      - partial: :text_field
        field: :location
      - partial: :number_pass_fail_comment
        field: :equipment_class
        attributes:
          min: 1
          max: 2
      - partial: :integer_comment
        field: :equipment_power
        attributes:
          min: 0
  - legend_i18n_key: visual_inspection
    fields:
      - partial: :pass_fail_comment
        field: :visual
      - partial: :pass_fail_comment
        field: :appliance_plug_check
  - legend_i18n_key: electrical_tests
    fields:
      - partial: :number_pass_fail_comment
        field: :fuse_rating
        attributes:
          min: 0
          max: 32
      - partial: :number_pass_fail_comment
        field: :earth_ohms
        attributes:
          min: 0
          step: 0.01
      - partial: :number_pass_fail_comment
        field: :insulation_mohms
        attributes:
          min: 0
      - partial: :number_pass_fail_comment
        field: :leakage_ma
        attributes:
          min: 0
          step: 0.01
  - legend_i18n_key: functional_tests
    fields:
      - partial: :pass_fail_comment
        field: :load_test
      - partial: :number_pass_fail_comment
        field: :rcd_trip_time_ms
        attributes:
          min: 0
          step: 0.01
